allowBuilds:
  '@parcel/watcher': true
  core-js: true
  million: true
  simple-git-hooks: true
  vue-demi: true
ignoreTrustChecks: true
minimumReleaseAgeExclude:
  - '@eslint-react/ast@5.8.9'
  - '@eslint-react/core@5.8.9'
  - '@eslint-react/eslint-plugin@5.8.9'
  - '@eslint-react/eslint@5.8.9'
  - '@eslint-react/jsx@5.8.9'
  - '@eslint-react/shared@5.8.9'
  - '@eslint-react/var@5.8.9'
  - '@react-grab/cli@0.1.44'
  - '@types/react@19.2.16'
  - eslint-plugin-react-dom@5.8.9
  - eslint-plugin-react-jsx@5.8.9
  - eslint-plugin-react-naming-convention@5.8.9
  - eslint-plugin-react-rsc@5.8.9
  - eslint-plugin-react-web-api@5.8.9
  - eslint-plugin-react-x@5.8.9
  - react-dom@19.2.7
  - react-grab@0.1.44
  - react@19.2.7
  - vite@8.0.16
shellEmulator: true

trustPolicy: no-downgrade
